// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ARESDbContext))]
    partial class ARESDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("DataAdmissao")
                        .HasColumnType("date");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cargo = "Analista",
                            DataAdmissao = new DateOnly(2020, 5, 1),
                            Matricula = "12345",
                            Nome = "Marcela"
                        },
                        new
                        {
                            Id = 2,
                            Cargo = "Desenvolvedor",
                            DataAdmissao = new DateOnly(2019, 8, 15),
                            Matricula = "67890",
                            Nome = "Isabela"
                        },
                        new
                        {
                            Id = 3,
                            Cargo = "Estagiário",
                            DataAdmissao = new DateOnly(2023, 1, 10),
                            Matricula = "54321",
                            Nome = "João"
                        },
                        new
                        {
                            Id = 4,
                            Cargo = "Estagiário",
                            DataAdmissao = new DateOnly(2024, 1, 15),
                            Matricula = "76538",
                            Nome = "Schultz"
                        });
                });

            modelBuilder.Entity("Laboratorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigComputadores")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("QtdComputadores")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Laboratorios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConfigComputadores = "Intel i5, 8GB RAM",
                            Nome = "Lab A",
                            QtdComputadores = 10
                        },
                        new
                        {
                            Id = 2,
                            ConfigComputadores = "Intel i7, 16GB RAM",
                            Nome = "Lab B",
                            QtdComputadores = 12
                        },
                        new
                        {
                            Id = 3,
                            ConfigComputadores = "AMD Ryzen 5, 16GB RAM",
                            Nome = "Lab C",
                            QtdComputadores = 8
                        });
                });

            modelBuilder.Entity("Notebook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataAquisicao")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NPatrimonio")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("NPatrimonio")
                        .IsUnique();

                    b.ToTable("Notebooks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataAquisicao = new DateOnly(2025, 8, 10),
                            Descricao = "Dell XPS 13",
                            NPatrimonio = "NB001"
                        },
                        new
                        {
                            Id = 2,
                            DataAquisicao = new DateOnly(2025, 8, 5),
                            Descricao = "MacBook Pro",
                            NPatrimonio = "NB002"
                        },
                        new
                        {
                            Id = 3,
                            DataAquisicao = new DateOnly(2025, 8, 15),
                            Descricao = "Lenovo ThinkPad",
                            NPatrimonio = "NB003"
                        });
                });

            modelBuilder.Entity("ReservaLaboratorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataReserva")
                        .HasColumnType("date");

                    b.Property<int>("FkFuncionario")
                        .HasColumnType("int");

                    b.Property<int>("FkLaboratorio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FkFuncionario");

                    b.HasIndex("FkLaboratorio");

                    b.ToTable("ReservaLaboratorios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataReserva = new DateOnly(2025, 7, 28),
                            FkFuncionario = 1,
                            FkLaboratorio = 1
                        },
                        new
                        {
                            Id = 2,
                            DataReserva = new DateOnly(2025, 8, 3),
                            FkFuncionario = 2,
                            FkLaboratorio = 2
                        },
                        new
                        {
                            Id = 3,
                            DataReserva = new DateOnly(2025, 8, 3),
                            FkFuncionario = 3,
                            FkLaboratorio = 3
                        },
                        new
                        {
                            Id = 4,
                            DataReserva = new DateOnly(2025, 8, 5),
                            FkFuncionario = 4,
                            FkLaboratorio = 1
                        },
                        new
                        {
                            Id = 5,
                            DataReserva = new DateOnly(2025, 8, 7),
                            FkFuncionario = 1,
                            FkLaboratorio = 2
                        },
                        new
                        {
                            Id = 6,
                            DataReserva = new DateOnly(2025, 8, 8),
                            FkFuncionario = 2,
                            FkLaboratorio = 3
                        },
                        new
                        {
                            Id = 7,
                            DataReserva = new DateOnly(2025, 8, 11),
                            FkFuncionario = 3,
                            FkLaboratorio = 1
                        },
                        new
                        {
                            Id = 8,
                            DataReserva = new DateOnly(2025, 8, 14),
                            FkFuncionario = 4,
                            FkLaboratorio = 2
                        },
                        new
                        {
                            Id = 9,
                            DataReserva = new DateOnly(2025, 8, 14),
                            FkFuncionario = 1,
                            FkLaboratorio = 3
                        },
                        new
                        {
                            Id = 10,
                            DataReserva = new DateOnly(2025, 8, 14),
                            FkFuncionario = 2,
                            FkLaboratorio = 1
                        },
                        new
                        {
                            Id = 11,
                            DataReserva = new DateOnly(2025, 8, 18),
                            FkFuncionario = 3,
                            FkLaboratorio = 2
                        },
                        new
                        {
                            Id = 12,
                            DataReserva = new DateOnly(2025, 8, 19),
                            FkFuncionario = 4,
                            FkLaboratorio = 3
                        },
                        new
                        {
                            Id = 13,
                            DataReserva = new DateOnly(2025, 8, 21),
                            FkFuncionario = 1,
                            FkLaboratorio = 1
                        },
                        new
                        {
                            Id = 14,
                            DataReserva = new DateOnly(2025, 8, 22),
                            FkFuncionario = 2,
                            FkLaboratorio = 2
                        },
                        new
                        {
                            Id = 15,
                            DataReserva = new DateOnly(2025, 8, 25),
                            FkFuncionario = 3,
                            FkLaboratorio = 3
                        },
                        new
                        {
                            Id = 16,
                            DataReserva = new DateOnly(2025, 8, 26),
                            FkFuncionario = 4,
                            FkLaboratorio = 1
                        },
                        new
                        {
                            Id = 17,
                            DataReserva = new DateOnly(2025, 8, 28),
                            FkFuncionario = 1,
                            FkLaboratorio = 2
                        },
                        new
                        {
                            Id = 18,
                            DataReserva = new DateOnly(2025, 8, 29),
                            FkFuncionario = 2,
                            FkLaboratorio = 3
                        },
                        new
                        {
                            Id = 19,
                            DataReserva = new DateOnly(2025, 9, 2),
                            FkFuncionario = 3,
                            FkLaboratorio = 1
                        },
                        new
                        {
                            Id = 20,
                            DataReserva = new DateOnly(2025, 9, 2),
                            FkFuncionario = 4,
                            FkLaboratorio = 2
                        },
                        new
                        {
                            Id = 21,
                            DataReserva = new DateOnly(2025, 8, 1),
                            FkFuncionario = 4,
                            FkLaboratorio = 2
                        },
                        new
                        {
                            Id = 22,
                            DataReserva = new DateOnly(2025, 8, 3),
                            FkFuncionario = 1,
                            FkLaboratorio = 1
                        },
                        new
                        {
                            Id = 23,
                            DataReserva = new DateOnly(2025, 8, 3),
                            FkFuncionario = 2,
                            FkLaboratorio = 3
                        },
                        new
                        {
                            Id = 24,
                            DataReserva = new DateOnly(2025, 8, 5),
                            FkFuncionario = 3,
                            FkLaboratorio = 2
                        },
                        new
                        {
                            Id = 25,
                            DataReserva = new DateOnly(2025, 8, 6),
                            FkFuncionario = 4,
                            FkLaboratorio = 1
                        },
                        new
                        {
                            Id = 26,
                            DataReserva = new DateOnly(2025, 8, 8),
                            FkFuncionario = 1,
                            FkLaboratorio = 3
                        },
                        new
                        {
                            Id = 27,
                            DataReserva = new DateOnly(2025, 8, 8),
                            FkFuncionario = 2,
                            FkLaboratorio = 2
                        },
                        new
                        {
                            Id = 28,
                            DataReserva = new DateOnly(2025, 8, 12),
                            FkFuncionario = 3,
                            FkLaboratorio = 1
                        },
                        new
                        {
                            Id = 29,
                            DataReserva = new DateOnly(2025, 8, 14),
                            FkFuncionario = 4,
                            FkLaboratorio = 3
                        },
                        new
                        {
                            Id = 30,
                            DataReserva = new DateOnly(2025, 8, 14),
                            FkFuncionario = 1,
                            FkLaboratorio = 2
                        },
                        new
                        {
                            Id = 31,
                            DataReserva = new DateOnly(2025, 8, 14),
                            FkFuncionario = 2,
                            FkLaboratorio = 1
                        },
                        new
                        {
                            Id = 32,
                            DataReserva = new DateOnly(2025, 8, 15),
                            FkFuncionario = 3,
                            FkLaboratorio = 3
                        },
                        new
                        {
                            Id = 33,
                            DataReserva = new DateOnly(2025, 8, 19),
                            FkFuncionario = 4,
                            FkLaboratorio = 2
                        },
                        new
                        {
                            Id = 34,
                            DataReserva = new DateOnly(2025, 8, 20),
                            FkFuncionario = 1,
                            FkLaboratorio = 1
                        },
                        new
                        {
                            Id = 35,
                            DataReserva = new DateOnly(2025, 8, 20),
                            FkFuncionario = 2,
                            FkLaboratorio = 3
                        },
                        new
                        {
                            Id = 36,
                            DataReserva = new DateOnly(2025, 8, 21),
                            FkFuncionario = 3,
                            FkLaboratorio = 2
                        },
                        new
                        {
                            Id = 37,
                            DataReserva = new DateOnly(2025, 8, 23),
                            FkFuncionario = 4,
                            FkLaboratorio = 1
                        },
                        new
                        {
                            Id = 38,
                            DataReserva = new DateOnly(2025, 8, 26),
                            FkFuncionario = 1,
                            FkLaboratorio = 3
                        },
                        new
                        {
                            Id = 39,
                            DataReserva = new DateOnly(2025, 8, 27),
                            FkFuncionario = 2,
                            FkLaboratorio = 2
                        },
                        new
                        {
                            Id = 40,
                            DataReserva = new DateOnly(2025, 8, 28),
                            FkFuncionario = 3,
                            FkLaboratorio = 1
                        },
                        new
                        {
                            Id = 41,
                            DataReserva = new DateOnly(2025, 8, 28),
                            FkFuncionario = 4,
                            FkLaboratorio = 3
                        },
                        new
                        {
                            Id = 42,
                            DataReserva = new DateOnly(2025, 8, 28),
                            FkFuncionario = 1,
                            FkLaboratorio = 2
                        },
                        new
                        {
                            Id = 43,
                            DataReserva = new DateOnly(2025, 8, 29),
                            FkFuncionario = 2,
                            FkLaboratorio = 1
                        },
                        new
                        {
                            Id = 44,
                            DataReserva = new DateOnly(2025, 8, 30),
                            FkFuncionario = 3,
                            FkLaboratorio = 3
                        },
                        new
                        {
                            Id = 45,
                            DataReserva = new DateOnly(2025, 9, 2),
                            FkFuncionario = 4,
                            FkLaboratorio = 2
                        },
                        new
                        {
                            Id = 46,
                            DataReserva = new DateOnly(2025, 9, 4),
                            FkFuncionario = 1,
                            FkLaboratorio = 1
                        },
                        new
                        {
                            Id = 47,
                            DataReserva = new DateOnly(2025, 9, 5),
                            FkFuncionario = 2,
                            FkLaboratorio = 3
                        },
                        new
                        {
                            Id = 48,
                            DataReserva = new DateOnly(2025, 9, 5),
                            FkFuncionario = 3,
                            FkLaboratorio = 2
                        },
                        new
                        {
                            Id = 49,
                            DataReserva = new DateOnly(2025, 9, 8),
                            FkFuncionario = 4,
                            FkLaboratorio = 1
                        },
                        new
                        {
                            Id = 50,
                            DataReserva = new DateOnly(2025, 9, 8),
                            FkFuncionario = 1,
                            FkLaboratorio = 3
                        },
                        new
                        {
                            Id = 51,
                            DataReserva = new DateOnly(2025, 9, 8),
                            FkFuncionario = 2,
                            FkLaboratorio = 2
                        },
                        new
                        {
                            Id = 52,
                            DataReserva = new DateOnly(2025, 9, 10),
                            FkFuncionario = 3,
                            FkLaboratorio = 1
                        },
                        new
                        {
                            Id = 53,
                            DataReserva = new DateOnly(2025, 9, 12),
                            FkFuncionario = 4,
                            FkLaboratorio = 3
                        },
                        new
                        {
                            Id = 54,
                            DataReserva = new DateOnly(2025, 9, 13),
                            FkFuncionario = 1,
                            FkLaboratorio = 2
                        },
                        new
                        {
                            Id = 55,
                            DataReserva = new DateOnly(2025, 9, 15),
                            FkFuncionario = 2,
                            FkLaboratorio = 1
                        },
                        new
                        {
                            Id = 56,
                            DataReserva = new DateOnly(2025, 9, 15),
                            FkFuncionario = 3,
                            FkLaboratorio = 3
                        },
                        new
                        {
                            Id = 57,
                            DataReserva = new DateOnly(2025, 9, 17),
                            FkFuncionario = 4,
                            FkLaboratorio = 2
                        },
                        new
                        {
                            Id = 58,
                            DataReserva = new DateOnly(2025, 9, 19),
                            FkFuncionario = 1,
                            FkLaboratorio = 1
                        },
                        new
                        {
                            Id = 59,
                            DataReserva = new DateOnly(2025, 9, 21),
                            FkFuncionario = 2,
                            FkLaboratorio = 3
                        },
                        new
                        {
                            Id = 60,
                            DataReserva = new DateOnly(2025, 9, 21),
                            FkFuncionario = 3,
                            FkLaboratorio = 2
                        },
                        new
                        {
                            Id = 61,
                            DataReserva = new DateOnly(2025, 9, 23),
                            FkFuncionario = 4,
                            FkLaboratorio = 1
                        },
                        new
                        {
                            Id = 62,
                            DataReserva = new DateOnly(2025, 9, 24),
                            FkFuncionario = 1,
                            FkLaboratorio = 3
                        },
                        new
                        {
                            Id = 63,
                            DataReserva = new DateOnly(2025, 9, 24),
                            FkFuncionario = 2,
                            FkLaboratorio = 2
                        },
                        new
                        {
                            Id = 64,
                            DataReserva = new DateOnly(2025, 9, 24),
                            FkFuncionario = 3,
                            FkLaboratorio = 1
                        },
                        new
                        {
                            Id = 65,
                            DataReserva = new DateOnly(2025, 9, 26),
                            FkFuncionario = 4,
                            FkLaboratorio = 3
                        },
                        new
                        {
                            Id = 66,
                            DataReserva = new DateOnly(2025, 9, 27),
                            FkFuncionario = 1,
                            FkLaboratorio = 2
                        },
                        new
                        {
                            Id = 67,
                            DataReserva = new DateOnly(2025, 9, 28),
                            FkFuncionario = 2,
                            FkLaboratorio = 1
                        },
                        new
                        {
                            Id = 68,
                            DataReserva = new DateOnly(2025, 9, 28),
                            FkFuncionario = 3,
                            FkLaboratorio = 3
                        },
                        new
                        {
                            Id = 69,
                            DataReserva = new DateOnly(2025, 9, 29),
                            FkFuncionario = 4,
                            FkLaboratorio = 2
                        },
                        new
                        {
                            Id = 70,
                            DataReserva = new DateOnly(2025, 9, 30),
                            FkFuncionario = 1,
                            FkLaboratorio = 1
                        });
                });

            modelBuilder.Entity("ReservaNotebook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataReserva")
                        .HasColumnType("date");

                    b.Property<int>("FkFuncionario")
                        .HasColumnType("int");

                    b.Property<int>("FkNotebook")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FkFuncionario");

                    b.HasIndex("FkNotebook");

                    b.ToTable("ReservaNotebooks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataReserva = new DateOnly(2025, 7, 29),
                            FkFuncionario = 2,
                            FkNotebook = 1
                        },
                        new
                        {
                            Id = 2,
                            DataReserva = new DateOnly(2025, 8, 2),
                            FkFuncionario = 3,
                            FkNotebook = 2
                        },
                        new
                        {
                            Id = 3,
                            DataReserva = new DateOnly(2025, 8, 4),
                            FkFuncionario = 4,
                            FkNotebook = 3
                        },
                        new
                        {
                            Id = 4,
                            DataReserva = new DateOnly(2025, 8, 4),
                            FkFuncionario = 1,
                            FkNotebook = 1
                        },
                        new
                        {
                            Id = 5,
                            DataReserva = new DateOnly(2025, 8, 9),
                            FkFuncionario = 2,
                            FkNotebook = 2
                        },
                        new
                        {
                            Id = 6,
                            DataReserva = new DateOnly(2025, 8, 10),
                            FkFuncionario = 3,
                            FkNotebook = 3
                        },
                        new
                        {
                            Id = 7,
                            DataReserva = new DateOnly(2025, 8, 13),
                            FkFuncionario = 4,
                            FkNotebook = 1
                        },
                        new
                        {
                            Id = 8,
                            DataReserva = new DateOnly(2025, 8, 15),
                            FkFuncionario = 1,
                            FkNotebook = 2
                        },
                        new
                        {
                            Id = 9,
                            DataReserva = new DateOnly(2025, 8, 16),
                            FkFuncionario = 2,
                            FkNotebook = 3
                        },
                        new
                        {
                            Id = 10,
                            DataReserva = new DateOnly(2025, 8, 16),
                            FkFuncionario = 3,
                            FkNotebook = 1
                        },
                        new
                        {
                            Id = 11,
                            DataReserva = new DateOnly(2025, 8, 20),
                            FkFuncionario = 4,
                            FkNotebook = 2
                        },
                        new
                        {
                            Id = 12,
                            DataReserva = new DateOnly(2025, 8, 26),
                            FkFuncionario = 1,
                            FkNotebook = 3
                        },
                        new
                        {
                            Id = 13,
                            DataReserva = new DateOnly(2025, 8, 26),
                            FkFuncionario = 2,
                            FkNotebook = 1
                        },
                        new
                        {
                            Id = 14,
                            DataReserva = new DateOnly(2025, 8, 26),
                            FkFuncionario = 3,
                            FkNotebook = 2
                        },
                        new
                        {
                            Id = 15,
                            DataReserva = new DateOnly(2025, 8, 27),
                            FkFuncionario = 4,
                            FkNotebook = 3
                        },
                        new
                        {
                            Id = 16,
                            DataReserva = new DateOnly(2025, 8, 30),
                            FkFuncionario = 1,
                            FkNotebook = 1
                        },
                        new
                        {
                            Id = 17,
                            DataReserva = new DateOnly(2025, 8, 30),
                            FkFuncionario = 2,
                            FkNotebook = 2
                        },
                        new
                        {
                            Id = 18,
                            DataReserva = new DateOnly(2025, 9, 1),
                            FkFuncionario = 3,
                            FkNotebook = 3
                        },
                        new
                        {
                            Id = 19,
                            DataReserva = new DateOnly(2025, 9, 2),
                            FkFuncionario = 4,
                            FkNotebook = 1
                        },
                        new
                        {
                            Id = 20,
                            DataReserva = new DateOnly(2025, 9, 2),
                            FkFuncionario = 1,
                            FkNotebook = 2
                        },
                        new
                        {
                            Id = 21,
                            DataReserva = new DateOnly(2025, 8, 1),
                            FkFuncionario = 2,
                            FkNotebook = 3
                        },
                        new
                        {
                            Id = 22,
                            DataReserva = new DateOnly(2025, 8, 2),
                            FkFuncionario = 3,
                            FkNotebook = 1
                        },
                        new
                        {
                            Id = 23,
                            DataReserva = new DateOnly(2025, 8, 4),
                            FkFuncionario = 4,
                            FkNotebook = 2
                        },
                        new
                        {
                            Id = 24,
                            DataReserva = new DateOnly(2025, 8, 5),
                            FkFuncionario = 1,
                            FkNotebook = 3
                        },
                        new
                        {
                            Id = 25,
                            DataReserva = new DateOnly(2025, 8, 6),
                            FkFuncionario = 2,
                            FkNotebook = 1
                        },
                        new
                        {
                            Id = 26,
                            DataReserva = new DateOnly(2025, 8, 8),
                            FkFuncionario = 3,
                            FkNotebook = 2
                        },
                        new
                        {
                            Id = 27,
                            DataReserva = new DateOnly(2025, 8, 9),
                            FkFuncionario = 4,
                            FkNotebook = 3
                        },
                        new
                        {
                            Id = 28,
                            DataReserva = new DateOnly(2025, 8, 9),
                            FkFuncionario = 1,
                            FkNotebook = 1
                        },
                        new
                        {
                            Id = 29,
                            DataReserva = new DateOnly(2025, 8, 11),
                            FkFuncionario = 2,
                            FkNotebook = 2
                        },
                        new
                        {
                            Id = 30,
                            DataReserva = new DateOnly(2025, 8, 13),
                            FkFuncionario = 3,
                            FkNotebook = 3
                        },
                        new
                        {
                            Id = 31,
                            DataReserva = new DateOnly(2025, 8, 14),
                            FkFuncionario = 4,
                            FkNotebook = 1
                        },
                        new
                        {
                            Id = 32,
                            DataReserva = new DateOnly(2025, 8, 15),
                            FkFuncionario = 1,
                            FkNotebook = 2
                        },
                        new
                        {
                            Id = 33,
                            DataReserva = new DateOnly(2025, 8, 16),
                            FkFuncionario = 2,
                            FkNotebook = 3
                        },
                        new
                        {
                            Id = 34,
                            DataReserva = new DateOnly(2025, 8, 18),
                            FkFuncionario = 3,
                            FkNotebook = 1
                        },
                        new
                        {
                            Id = 35,
                            DataReserva = new DateOnly(2025, 8, 19),
                            FkFuncionario = 4,
                            FkNotebook = 2
                        },
                        new
                        {
                            Id = 36,
                            DataReserva = new DateOnly(2025, 8, 20),
                            FkFuncionario = 1,
                            FkNotebook = 3
                        },
                        new
                        {
                            Id = 37,
                            DataReserva = new DateOnly(2025, 8, 21),
                            FkFuncionario = 2,
                            FkNotebook = 1
                        },
                        new
                        {
                            Id = 38,
                            DataReserva = new DateOnly(2025, 8, 23),
                            FkFuncionario = 3,
                            FkNotebook = 2
                        },
                        new
                        {
                            Id = 39,
                            DataReserva = new DateOnly(2025, 8, 24),
                            FkFuncionario = 4,
                            FkNotebook = 3
                        },
                        new
                        {
                            Id = 40,
                            DataReserva = new DateOnly(2025, 8, 24),
                            FkFuncionario = 1,
                            FkNotebook = 1
                        },
                        new
                        {
                            Id = 41,
                            DataReserva = new DateOnly(2025, 8, 25),
                            FkFuncionario = 2,
                            FkNotebook = 2
                        },
                        new
                        {
                            Id = 42,
                            DataReserva = new DateOnly(2025, 8, 27),
                            FkFuncionario = 3,
                            FkNotebook = 3
                        },
                        new
                        {
                            Id = 43,
                            DataReserva = new DateOnly(2025, 8, 28),
                            FkFuncionario = 4,
                            FkNotebook = 1
                        },
                        new
                        {
                            Id = 44,
                            DataReserva = new DateOnly(2025, 8, 29),
                            FkFuncionario = 1,
                            FkNotebook = 2
                        },
                        new
                        {
                            Id = 45,
                            DataReserva = new DateOnly(2025, 8, 30),
                            FkFuncionario = 2,
                            FkNotebook = 3
                        },
                        new
                        {
                            Id = 46,
                            DataReserva = new DateOnly(2025, 9, 1),
                            FkFuncionario = 3,
                            FkNotebook = 1
                        },
                        new
                        {
                            Id = 47,
                            DataReserva = new DateOnly(2025, 9, 2),
                            FkFuncionario = 4,
                            FkNotebook = 2
                        },
                        new
                        {
                            Id = 48,
                            DataReserva = new DateOnly(2025, 9, 3),
                            FkFuncionario = 1,
                            FkNotebook = 3
                        },
                        new
                        {
                            Id = 49,
                            DataReserva = new DateOnly(2025, 9, 4),
                            FkFuncionario = 2,
                            FkNotebook = 1
                        },
                        new
                        {
                            Id = 50,
                            DataReserva = new DateOnly(2025, 9, 5),
                            FkFuncionario = 3,
                            FkNotebook = 2
                        },
                        new
                        {
                            Id = 51,
                            DataReserva = new DateOnly(2025, 9, 7),
                            FkFuncionario = 4,
                            FkNotebook = 3
                        },
                        new
                        {
                            Id = 52,
                            DataReserva = new DateOnly(2025, 9, 9),
                            FkFuncionario = 1,
                            FkNotebook = 1
                        },
                        new
                        {
                            Id = 53,
                            DataReserva = new DateOnly(2025, 9, 10),
                            FkFuncionario = 2,
                            FkNotebook = 2
                        },
                        new
                        {
                            Id = 54,
                            DataReserva = new DateOnly(2025, 9, 12),
                            FkFuncionario = 3,
                            FkNotebook = 3
                        },
                        new
                        {
                            Id = 55,
                            DataReserva = new DateOnly(2025, 9, 13),
                            FkFuncionario = 4,
                            FkNotebook = 1
                        },
                        new
                        {
                            Id = 56,
                            DataReserva = new DateOnly(2025, 9, 15),
                            FkFuncionario = 1,
                            FkNotebook = 2
                        },
                        new
                        {
                            Id = 57,
                            DataReserva = new DateOnly(2025, 9, 16),
                            FkFuncionario = 2,
                            FkNotebook = 3
                        },
                        new
                        {
                            Id = 58,
                            DataReserva = new DateOnly(2025, 9, 18),
                            FkFuncionario = 3,
                            FkNotebook = 1
                        },
                        new
                        {
                            Id = 59,
                            DataReserva = new DateOnly(2025, 9, 18),
                            FkFuncionario = 4,
                            FkNotebook = 2
                        },
                        new
                        {
                            Id = 60,
                            DataReserva = new DateOnly(2025, 9, 20),
                            FkFuncionario = 1,
                            FkNotebook = 3
                        },
                        new
                        {
                            Id = 61,
                            DataReserva = new DateOnly(2025, 9, 22),
                            FkFuncionario = 2,
                            FkNotebook = 1
                        },
                        new
                        {
                            Id = 62,
                            DataReserva = new DateOnly(2025, 9, 23),
                            FkFuncionario = 3,
                            FkNotebook = 2
                        },
                        new
                        {
                            Id = 63,
                            DataReserva = new DateOnly(2025, 9, 25),
                            FkFuncionario = 4,
                            FkNotebook = 3
                        },
                        new
                        {
                            Id = 64,
                            DataReserva = new DateOnly(2025, 9, 26),
                            FkFuncionario = 1,
                            FkNotebook = 1
                        },
                        new
                        {
                            Id = 65,
                            DataReserva = new DateOnly(2025, 9, 27),
                            FkFuncionario = 2,
                            FkNotebook = 2
                        },
                        new
                        {
                            Id = 66,
                            DataReserva = new DateOnly(2025, 9, 27),
                            FkFuncionario = 3,
                            FkNotebook = 3
                        },
                        new
                        {
                            Id = 67,
                            DataReserva = new DateOnly(2025, 9, 28),
                            FkFuncionario = 4,
                            FkNotebook = 1
                        },
                        new
                        {
                            Id = 68,
                            DataReserva = new DateOnly(2025, 9, 29),
                            FkFuncionario = 1,
                            FkNotebook = 2
                        },
                        new
                        {
                            Id = 69,
                            DataReserva = new DateOnly(2025, 9, 30),
                            FkFuncionario = 2,
                            FkNotebook = 3
                        },
                        new
                        {
                            Id = 70,
                            DataReserva = new DateOnly(2025, 9, 30),
                            FkFuncionario = 3,
                            FkNotebook = 1
                        });
                });

            modelBuilder.Entity("ReservaSala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataReserva")
                        .HasColumnType("date");

                    b.Property<int>("FkFuncionario")
                        .HasColumnType("int");

                    b.Property<int>("FkSala")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FkFuncionario");

                    b.HasIndex("FkSala");

                    b.ToTable("ReservaSalas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataReserva = new DateOnly(2025, 7, 30),
                            FkFuncionario = 3,
                            FkSala = 1
                        },
                        new
                        {
                            Id = 2,
                            DataReserva = new DateOnly(2025, 7, 30),
                            FkFuncionario = 4,
                            FkSala = 2
                        },
                        new
                        {
                            Id = 3,
                            DataReserva = new DateOnly(2025, 8, 3),
                            FkFuncionario = 1,
                            FkSala = 3
                        },
                        new
                        {
                            Id = 4,
                            DataReserva = new DateOnly(2025, 8, 5),
                            FkFuncionario = 2,
                            FkSala = 1
                        },
                        new
                        {
                            Id = 5,
                            DataReserva = new DateOnly(2025, 8, 6),
                            FkFuncionario = 3,
                            FkSala = 2
                        },
                        new
                        {
                            Id = 6,
                            DataReserva = new DateOnly(2025, 8, 9),
                            FkFuncionario = 4,
                            FkSala = 3
                        },
                        new
                        {
                            Id = 7,
                            DataReserva = new DateOnly(2025, 8, 9),
                            FkFuncionario = 1,
                            FkSala = 1
                        },
                        new
                        {
                            Id = 8,
                            DataReserva = new DateOnly(2025, 8, 9),
                            FkFuncionario = 2,
                            FkSala = 2
                        },
                        new
                        {
                            Id = 9,
                            DataReserva = new DateOnly(2025, 8, 12),
                            FkFuncionario = 3,
                            FkSala = 3
                        },
                        new
                        {
                            Id = 10,
                            DataReserva = new DateOnly(2025, 8, 14),
                            FkFuncionario = 4,
                            FkSala = 1
                        },
                        new
                        {
                            Id = 11,
                            DataReserva = new DateOnly(2025, 8, 15),
                            FkFuncionario = 1,
                            FkSala = 2
                        },
                        new
                        {
                            Id = 12,
                            DataReserva = new DateOnly(2025, 8, 17),
                            FkFuncionario = 2,
                            FkSala = 3
                        },
                        new
                        {
                            Id = 13,
                            DataReserva = new DateOnly(2025, 8, 19),
                            FkFuncionario = 3,
                            FkSala = 1
                        },
                        new
                        {
                            Id = 14,
                            DataReserva = new DateOnly(2025, 8, 20),
                            FkFuncionario = 4,
                            FkSala = 2
                        },
                        new
                        {
                            Id = 15,
                            DataReserva = new DateOnly(2025, 8, 22),
                            FkFuncionario = 1,
                            FkSala = 3
                        },
                        new
                        {
                            Id = 16,
                            DataReserva = new DateOnly(2025, 8, 25),
                            FkFuncionario = 2,
                            FkSala = 1
                        },
                        new
                        {
                            Id = 17,
                            DataReserva = new DateOnly(2025, 8, 25),
                            FkFuncionario = 3,
                            FkSala = 2
                        },
                        new
                        {
                            Id = 18,
                            DataReserva = new DateOnly(2025, 8, 26),
                            FkFuncionario = 4,
                            FkSala = 3
                        },
                        new
                        {
                            Id = 19,
                            DataReserva = new DateOnly(2025, 9, 1),
                            FkFuncionario = 1,
                            FkSala = 1
                        },
                        new
                        {
                            Id = 20,
                            DataReserva = new DateOnly(2025, 9, 3),
                            FkFuncionario = 2,
                            FkSala = 2
                        },
                        new
                        {
                            Id = 21,
                            DataReserva = new DateOnly(2025, 7, 31),
                            FkFuncionario = 3,
                            FkSala = 3
                        },
                        new
                        {
                            Id = 22,
                            DataReserva = new DateOnly(2025, 8, 2),
                            FkFuncionario = 4,
                            FkSala = 1
                        },
                        new
                        {
                            Id = 23,
                            DataReserva = new DateOnly(2025, 8, 4),
                            FkFuncionario = 1,
                            FkSala = 2
                        },
                        new
                        {
                            Id = 24,
                            DataReserva = new DateOnly(2025, 8, 5),
                            FkFuncionario = 2,
                            FkSala = 3
                        },
                        new
                        {
                            Id = 25,
                            DataReserva = new DateOnly(2025, 8, 5),
                            FkFuncionario = 3,
                            FkSala = 1
                        },
                        new
                        {
                            Id = 26,
                            DataReserva = new DateOnly(2025, 8, 8),
                            FkFuncionario = 4,
                            FkSala = 2
                        },
                        new
                        {
                            Id = 27,
                            DataReserva = new DateOnly(2025, 8, 8),
                            FkFuncionario = 1,
                            FkSala = 3
                        },
                        new
                        {
                            Id = 28,
                            DataReserva = new DateOnly(2025, 8, 12),
                            FkFuncionario = 2,
                            FkSala = 1
                        },
                        new
                        {
                            Id = 29,
                            DataReserva = new DateOnly(2025, 8, 14),
                            FkFuncionario = 3,
                            FkSala = 2
                        },
                        new
                        {
                            Id = 30,
                            DataReserva = new DateOnly(2025, 8, 15),
                            FkFuncionario = 4,
                            FkSala = 3
                        },
                        new
                        {
                            Id = 31,
                            DataReserva = new DateOnly(2025, 8, 15),
                            FkFuncionario = 1,
                            FkSala = 1
                        },
                        new
                        {
                            Id = 32,
                            DataReserva = new DateOnly(2025, 8, 15),
                            FkFuncionario = 2,
                            FkSala = 2
                        },
                        new
                        {
                            Id = 33,
                            DataReserva = new DateOnly(2025, 8, 19),
                            FkFuncionario = 3,
                            FkSala = 3
                        },
                        new
                        {
                            Id = 34,
                            DataReserva = new DateOnly(2025, 8, 20),
                            FkFuncionario = 4,
                            FkSala = 1
                        },
                        new
                        {
                            Id = 35,
                            DataReserva = new DateOnly(2025, 8, 21),
                            FkFuncionario = 1,
                            FkSala = 2
                        },
                        new
                        {
                            Id = 36,
                            DataReserva = new DateOnly(2025, 8, 23),
                            FkFuncionario = 2,
                            FkSala = 3
                        },
                        new
                        {
                            Id = 37,
                            DataReserva = new DateOnly(2025, 8, 24),
                            FkFuncionario = 3,
                            FkSala = 1
                        },
                        new
                        {
                            Id = 38,
                            DataReserva = new DateOnly(2025, 8, 27),
                            FkFuncionario = 4,
                            FkSala = 2
                        },
                        new
                        {
                            Id = 39,
                            DataReserva = new DateOnly(2025, 8, 28),
                            FkFuncionario = 1,
                            FkSala = 3
                        },
                        new
                        {
                            Id = 40,
                            DataReserva = new DateOnly(2025, 8, 29),
                            FkFuncionario = 2,
                            FkSala = 1
                        },
                        new
                        {
                            Id = 41,
                            DataReserva = new DateOnly(2025, 8, 30),
                            FkFuncionario = 3,
                            FkSala = 2
                        },
                        new
                        {
                            Id = 42,
                            DataReserva = new DateOnly(2025, 9, 1),
                            FkFuncionario = 4,
                            FkSala = 3
                        },
                        new
                        {
                            Id = 43,
                            DataReserva = new DateOnly(2025, 9, 3),
                            FkFuncionario = 1,
                            FkSala = 1
                        },
                        new
                        {
                            Id = 44,
                            DataReserva = new DateOnly(2025, 9, 4),
                            FkFuncionario = 2,
                            FkSala = 2
                        },
                        new
                        {
                            Id = 45,
                            DataReserva = new DateOnly(2025, 9, 5),
                            FkFuncionario = 3,
                            FkSala = 3
                        },
                        new
                        {
                            Id = 46,
                            DataReserva = new DateOnly(2025, 9, 6),
                            FkFuncionario = 4,
                            FkSala = 1
                        },
                        new
                        {
                            Id = 47,
                            DataReserva = new DateOnly(2025, 9, 8),
                            FkFuncionario = 1,
                            FkSala = 2
                        },
                        new
                        {
                            Id = 48,
                            DataReserva = new DateOnly(2025, 9, 9),
                            FkFuncionario = 2,
                            FkSala = 3
                        },
                        new
                        {
                            Id = 49,
                            DataReserva = new DateOnly(2025, 9, 10),
                            FkFuncionario = 3,
                            FkSala = 1
                        },
                        new
                        {
                            Id = 50,
                            DataReserva = new DateOnly(2025, 9, 11),
                            FkFuncionario = 4,
                            FkSala = 2
                        },
                        new
                        {
                            Id = 51,
                            DataReserva = new DateOnly(2025, 9, 12),
                            FkFuncionario = 1,
                            FkSala = 3
                        },
                        new
                        {
                            Id = 52,
                            DataReserva = new DateOnly(2025, 9, 14),
                            FkFuncionario = 2,
                            FkSala = 1
                        },
                        new
                        {
                            Id = 53,
                            DataReserva = new DateOnly(2025, 9, 15),
                            FkFuncionario = 3,
                            FkSala = 2
                        },
                        new
                        {
                            Id = 54,
                            DataReserva = new DateOnly(2025, 9, 16),
                            FkFuncionario = 4,
                            FkSala = 3
                        },
                        new
                        {
                            Id = 55,
                            DataReserva = new DateOnly(2025, 9, 17),
                            FkFuncionario = 1,
                            FkSala = 1
                        },
                        new
                        {
                            Id = 56,
                            DataReserva = new DateOnly(2025, 9, 18),
                            FkFuncionario = 2,
                            FkSala = 2
                        },
                        new
                        {
                            Id = 57,
                            DataReserva = new DateOnly(2025, 9, 19),
                            FkFuncionario = 3,
                            FkSala = 3
                        },
                        new
                        {
                            Id = 58,
                            DataReserva = new DateOnly(2025, 9, 20),
                            FkFuncionario = 4,
                            FkSala = 1
                        },
                        new
                        {
                            Id = 59,
                            DataReserva = new DateOnly(2025, 9, 22),
                            FkFuncionario = 1,
                            FkSala = 2
                        },
                        new
                        {
                            Id = 60,
                            DataReserva = new DateOnly(2025, 9, 22),
                            FkFuncionario = 2,
                            FkSala = 3
                        },
                        new
                        {
                            Id = 61,
                            DataReserva = new DateOnly(2025, 9, 23),
                            FkFuncionario = 3,
                            FkSala = 1
                        },
                        new
                        {
                            Id = 62,
                            DataReserva = new DateOnly(2025, 9, 25),
                            FkFuncionario = 4,
                            FkSala = 2
                        },
                        new
                        {
                            Id = 63,
                            DataReserva = new DateOnly(2025, 9, 25),
                            FkFuncionario = 1,
                            FkSala = 3
                        },
                        new
                        {
                            Id = 64,
                            DataReserva = new DateOnly(2025, 9, 26),
                            FkFuncionario = 2,
                            FkSala = 1
                        },
                        new
                        {
                            Id = 65,
                            DataReserva = new DateOnly(2025, 9, 27),
                            FkFuncionario = 3,
                            FkSala = 2
                        },
                        new
                        {
                            Id = 66,
                            DataReserva = new DateOnly(2025, 9, 28),
                            FkFuncionario = 4,
                            FkSala = 3
                        },
                        new
                        {
                            Id = 67,
                            DataReserva = new DateOnly(2025, 9, 28),
                            FkFuncionario = 1,
                            FkSala = 1
                        },
                        new
                        {
                            Id = 68,
                            DataReserva = new DateOnly(2025, 9, 29),
                            FkFuncionario = 2,
                            FkSala = 2
                        },
                        new
                        {
                            Id = 69,
                            DataReserva = new DateOnly(2025, 9, 29),
                            FkFuncionario = 3,
                            FkSala = 3
                        },
                        new
                        {
                            Id = 70,
                            DataReserva = new DateOnly(2025, 9, 30),
                            FkFuncionario = 4,
                            FkSala = 1
                        });
                });

            modelBuilder.Entity("Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NumeroSala")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<bool>("TemProjetor")
                        .HasColumnType("bit");

                    b.Property<int>("qtdLugares")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Salas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NumeroSala = "501",
                            TemProjetor = true,
                            qtdLugares = 40
                        },
                        new
                        {
                            Id = 2,
                            NumeroSala = "102",
                            TemProjetor = false,
                            qtdLugares = 30
                        },
                        new
                        {
                            Id = 3,
                            NumeroSala = "203",
                            TemProjetor = true,
                            qtdLugares = 20
                        });
                });

            modelBuilder.Entity("ReservaLaboratorio", b =>
                {
                    b.HasOne("Domain.Funcionario", "Funcionario")
                        .WithMany("ReservasLaboratorio")
                        .HasForeignKey("FkFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Laboratorio", "Laboratorio")
                        .WithMany("Reservas")
                        .HasForeignKey("FkLaboratorio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Laboratorio");
                });

            modelBuilder.Entity("ReservaNotebook", b =>
                {
                    b.HasOne("Domain.Funcionario", "Funcionario")
                        .WithMany("ReservasNotebook")
                        .HasForeignKey("FkFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Notebook", "Notebook")
                        .WithMany("Reservas")
                        .HasForeignKey("FkNotebook")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Notebook");
                });

            modelBuilder.Entity("ReservaSala", b =>
                {
                    b.HasOne("Domain.Funcionario", "Funcionario")
                        .WithMany("ReservasSala")
                        .HasForeignKey("FkFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sala", "Sala")
                        .WithMany("Reservas")
                        .HasForeignKey("FkSala")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Domain.Funcionario", b =>
                {
                    b.Navigation("ReservasLaboratorio");

                    b.Navigation("ReservasNotebook");

                    b.Navigation("ReservasSala");
                });

            modelBuilder.Entity("Laboratorio", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Notebook", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Sala", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
